const Constants = {
  CURRENT_USER: 'CURRENT_USER',
  USER_SIGNED_OUT: 'USER_SIGNED_OUT',

  REPOSITORIES_RECEIVED: 'REPOSITORIES_RECEIVED',
  REPOSITORIES_RESET: 'REPOSITORIES_RESET',
  REPOSITORIES_NEW_REPOSITORY_CREATED: 'REPOSITORIES_NEW_REPOSITORY_CREATED',

  CURRENT_REPOSITORY_RECEIVED: 'CURRENT_REPOSITORY_RECEIVED',
  CURRENT_REPOSITORY_BUILDS_RECEIVED: 'CURRENT_REPOSITORY_BUILDS_RECEIVED',

  CURRENT_BUILD_RECEIVED: 'CURRENT_BUILD_RECEIVED',
};

export default Constants;
